CREATE TABLE users (
  persist_key BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier VARCHAR(255) NOT NULL UNIQUE,
  email_identifier VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  bot_flag BOOLEAN NOT NULL,
  register_date TIMESTAMP WITH TIME ZONE NOT NULL,
  update_date TIMESTAMP WITH TIME ZONE NOT NULL
);
