CREATE TABLE user_access_token (
  persist_key BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_persist_key BIGINT NOT NULL,
  access_token VARCHAR(255) NOT NULL,
  source_update_date TIMESTAMP WITH TIME ZONE NOT NULL,
  register_date TIMESTAMP WITH TIME ZONE NOT NULL,
  expire_date TIMESTAMP WITH TIME ZONE NOT NULL
);
