CREATE TABLE company (
  persist_key BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  identifier VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  register_date TIMESTAMP WITH TIME ZONE NOT NULL
);
